// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package acme_endpoint

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}
	// An empty spec.certificateAuthority.publicCertificateAuthority ({})
	// means "issue from the public CA with no key algorithm restrictions".
	// The service stores nothing for it, so DescribeAcmeEndpoint omits
	// CertificateAuthority from its response entirely: absence on the AWS
	// side means "no restrictions", not missing data. The two
	// normalizations below reconcile that representation difference; a
	// genuine change to allowedKeyAlgorithms still produces a diff and
	// reconciles via UpdateAcmeEndpoint.

	// The user specified an empty publicCertificateAuthority and AWS
	// reports nothing: these mean the same thing, so mirror the desired
	// value into latest to suppress the diff (without this, {} vs nil
	// would fire a no-op UpdateAcmeEndpoint on every reconcile, forever).
	if a.ko.Spec.CertificateAuthority != nil && b.ko.Spec.CertificateAuthority == nil &&
		a.ko.Spec.CertificateAuthority.PublicCertificateAuthority != nil &&
		a.ko.Spec.CertificateAuthority.PublicCertificateAuthority.AllowedKeyAlgorithms == nil {
		b.ko.Spec.CertificateAuthority = a.ko.Spec.CertificateAuthority
	}

	// The user left allowedKeyAlgorithms unset but AWS reports values:
	// treat unset as "no opinion" and adopt what AWS reports, mirroring
	// late-initialization semantics without requiring the response to
	// always carry the field.
	if a.ko.Spec.CertificateAuthority != nil && b.ko.Spec.CertificateAuthority != nil &&
		a.ko.Spec.CertificateAuthority.PublicCertificateAuthority != nil &&
		b.ko.Spec.CertificateAuthority.PublicCertificateAuthority != nil &&
		a.ko.Spec.CertificateAuthority.PublicCertificateAuthority.AllowedKeyAlgorithms == nil {
		a.ko.Spec.CertificateAuthority.PublicCertificateAuthority.AllowedKeyAlgorithms =
			b.ko.Spec.CertificateAuthority.PublicCertificateAuthority.AllowedKeyAlgorithms
	}

	if ackcompare.HasNilDifference(a.ko.Spec.AuthorizationBehavior, b.ko.Spec.AuthorizationBehavior) {
		delta.Add("Spec.AuthorizationBehavior", a.ko.Spec.AuthorizationBehavior, b.ko.Spec.AuthorizationBehavior)
	} else if a.ko.Spec.AuthorizationBehavior != nil && b.ko.Spec.AuthorizationBehavior != nil {
		if *a.ko.Spec.AuthorizationBehavior != *b.ko.Spec.AuthorizationBehavior {
			delta.Add("Spec.AuthorizationBehavior", a.ko.Spec.AuthorizationBehavior, b.ko.Spec.AuthorizationBehavior)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.CertificateAuthority, b.ko.Spec.CertificateAuthority) {
		delta.Add("Spec.CertificateAuthority", a.ko.Spec.CertificateAuthority, b.ko.Spec.CertificateAuthority)
	} else if a.ko.Spec.CertificateAuthority != nil && b.ko.Spec.CertificateAuthority != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.CertificateAuthority.PublicCertificateAuthority, b.ko.Spec.CertificateAuthority.PublicCertificateAuthority) {
			delta.Add("Spec.CertificateAuthority.PublicCertificateAuthority", a.ko.Spec.CertificateAuthority.PublicCertificateAuthority, b.ko.Spec.CertificateAuthority.PublicCertificateAuthority)
		} else if a.ko.Spec.CertificateAuthority.PublicCertificateAuthority != nil && b.ko.Spec.CertificateAuthority.PublicCertificateAuthority != nil {
			if len(a.ko.Spec.CertificateAuthority.PublicCertificateAuthority.AllowedKeyAlgorithms) != len(b.ko.Spec.CertificateAuthority.PublicCertificateAuthority.AllowedKeyAlgorithms) {
				delta.Add("Spec.CertificateAuthority.PublicCertificateAuthority.AllowedKeyAlgorithms", a.ko.Spec.CertificateAuthority.PublicCertificateAuthority.AllowedKeyAlgorithms, b.ko.Spec.CertificateAuthority.PublicCertificateAuthority.AllowedKeyAlgorithms)
			} else if len(a.ko.Spec.CertificateAuthority.PublicCertificateAuthority.AllowedKeyAlgorithms) > 0 {
				if !ackcompare.SliceStringPEqual(a.ko.Spec.CertificateAuthority.PublicCertificateAuthority.AllowedKeyAlgorithms, b.ko.Spec.CertificateAuthority.PublicCertificateAuthority.AllowedKeyAlgorithms) {
					delta.Add("Spec.CertificateAuthority.PublicCertificateAuthority.AllowedKeyAlgorithms", a.ko.Spec.CertificateAuthority.PublicCertificateAuthority.AllowedKeyAlgorithms, b.ko.Spec.CertificateAuthority.PublicCertificateAuthority.AllowedKeyAlgorithms)
				}
			}
		}
	}
	if len(a.ko.Spec.CertificateTags) != len(b.ko.Spec.CertificateTags) {
		delta.Add("Spec.CertificateTags", a.ko.Spec.CertificateTags, b.ko.Spec.CertificateTags)
	} else if len(a.ko.Spec.CertificateTags) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.CertificateTags, b.ko.Spec.CertificateTags) {
			delta.Add("Spec.CertificateTags", a.ko.Spec.CertificateTags, b.ko.Spec.CertificateTags)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Contact, b.ko.Spec.Contact) {
		delta.Add("Spec.Contact", a.ko.Spec.Contact, b.ko.Spec.Contact)
	} else if a.ko.Spec.Contact != nil && b.ko.Spec.Contact != nil {
		if *a.ko.Spec.Contact != *b.ko.Spec.Contact {
			delta.Add("Spec.Contact", a.ko.Spec.Contact, b.ko.Spec.Contact)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
