// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AcmeEndpointSpec defines the desired state of AcmeEndpoint.
//
// Contains detailed information about an ACME endpoint.
type AcmeEndpointSpec struct {

	// The authorization behavior for the ACME endpoint. Valid values: PRE_APPROVED.
	//
	// The authorization behavior for the ACME endpoint.
	// +kubebuilder:validation:Required
	AuthorizationBehavior *string `json:"authorizationBehavior"`
	// The certificate authority to use for issuing certificates through this endpoint.
	// Currently only PublicCertificateAuthority (Amazon Trust Services) is supported.
	// Optionally specify AllowedKeyAlgorithms to restrict key algorithms for issued certificates.
	//
	// The type of certificate authority to use for issuing certificates through
	// this ACME endpoint.
	// +kubebuilder:validation:Required
	CertificateAuthority *CertificateAuthority `json:"certificateAuthority"`
	// Tags to apply to certificates issued through this ACME endpoint.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	CertificateTags []*Tag `json:"certificateTags,omitempty"`
	// Whether ACME clients must provide contact information during account registration.
	// Valid values: REQUIRED, NOT_REQUIRED.
	//
	// Specifies whether ACME clients must provide contact information during account
	// registration.
	Contact *string `json:"contact,omitempty"`
	// One or more tags to associate with the ACME endpoint.
	Tags []*Tag `json:"tags,omitempty"`
}

// AcmeEndpointStatus defines the observed state of AcmeEndpoint
type AcmeEndpointStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The Amazon Resource Name (ARN) of the ACME endpoint.
	//
	// Regex Pattern: `^arn:aws[a-z-]*:acm:[a-z0-9-]+:[0-9]{12}:acme-endpoint/[a-zA-Z0-9-]+$`
	// +kubebuilder:validation:Optional
	AcmeEndpointARN *string `json:"acmeEndpointARN,omitempty"`
	// The time at which the ACME endpoint was created.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The URL of the ACME endpoint.
	// +kubebuilder:validation:Optional
	EndpointURL *string `json:"endpointURL,omitempty"`
	// The reason the ACME endpoint failed, if applicable.
	// +kubebuilder:validation:Optional
	FailureReason *string `json:"failureReason,omitempty"`
	// The status of the ACME endpoint.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
	// The time at which the ACME endpoint was last updated.
	// +kubebuilder:validation:Optional
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
}

// AcmeEndpoint is the Schema for the AcmeEndpoints API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type AcmeEndpoint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AcmeEndpointSpec   `json:"spec,omitempty"`
	Status            AcmeEndpointStatus `json:"status,omitempty"`
}

// AcmeEndpointList contains a list of AcmeEndpoint
// +kubebuilder:object:root=true
type AcmeEndpointList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AcmeEndpoint `json:"items"`
}

func init() {
	SchemeBuilder.Register(&AcmeEndpoint{}, &AcmeEndpointList{})
}
