// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type AcmeAccountStatus string

const (
	AcmeAccountStatus_DEACTIVATED AcmeAccountStatus = "DEACTIVATED"
	AcmeAccountStatus_REVOKED     AcmeAccountStatus = "REVOKED"
	AcmeAccountStatus_VALID       AcmeAccountStatus = "VALID"
)

type AcmeAuthorizationBehavior string

const (
	AcmeAuthorizationBehavior_PRE_APPROVED AcmeAuthorizationBehavior = "PRE_APPROVED"
)

type AcmeContact string

const (
	AcmeContact_NOT_REQUIRED AcmeContact = "NOT_REQUIRED"
	AcmeContact_REQUIRED     AcmeContact = "REQUIRED"
)

type AcmeDomainValidationFailureReason string

const (
	AcmeDomainValidationFailureReason_ACCESS_DENIED         AcmeDomainValidationFailureReason = "ACCESS_DENIED"
	AcmeDomainValidationFailureReason_DOMAIN_MISMATCH       AcmeDomainValidationFailureReason = "DOMAIN_MISMATCH"
	AcmeDomainValidationFailureReason_DOMAIN_NOT_ALLOWED    AcmeDomainValidationFailureReason = "DOMAIN_NOT_ALLOWED"
	AcmeDomainValidationFailureReason_ENDPOINT_NOT_ACTIVE   AcmeDomainValidationFailureReason = "ENDPOINT_NOT_ACTIVE"
	AcmeDomainValidationFailureReason_HOSTED_ZONE_NOT_FOUND AcmeDomainValidationFailureReason = "HOSTED_ZONE_NOT_FOUND"
	AcmeDomainValidationFailureReason_INTERNAL_FAILURE      AcmeDomainValidationFailureReason = "INTERNAL_FAILURE"
	AcmeDomainValidationFailureReason_INVALID_CHANGE_BATCH  AcmeDomainValidationFailureReason = "INVALID_CHANGE_BATCH"
	AcmeDomainValidationFailureReason_INVALID_PUBLIC_DOMAIN AcmeDomainValidationFailureReason = "INVALID_PUBLIC_DOMAIN"
	AcmeDomainValidationFailureReason_TIMED_OUT             AcmeDomainValidationFailureReason = "TIMED_OUT"
)

type AcmeDomainValidationStatus string

const (
	AcmeDomainValidationStatus_DELETING   AcmeDomainValidationStatus = "DELETING"
	AcmeDomainValidationStatus_INVALID    AcmeDomainValidationStatus = "INVALID"
	AcmeDomainValidationStatus_VALID      AcmeDomainValidationStatus = "VALID"
	AcmeDomainValidationStatus_VALIDATING AcmeDomainValidationStatus = "VALIDATING"
)

type AcmeEndpointStatus string

const (
	AcmeEndpointStatus_ACTIVE   AcmeEndpointStatus = "ACTIVE"
	AcmeEndpointStatus_CREATING AcmeEndpointStatus = "CREATING"
	AcmeEndpointStatus_DELETING AcmeEndpointStatus = "DELETING"
	AcmeEndpointStatus_FAILED   AcmeEndpointStatus = "FAILED"
)

type CertificateExport string

const (
	CertificateExport_DISABLED CertificateExport = "DISABLED"
	CertificateExport_ENABLED  CertificateExport = "ENABLED"
)

type CertificateKeyPairOrigin string

const (
	CertificateKeyPairOrigin_ACME              CertificateKeyPairOrigin = "ACME"
	CertificateKeyPairOrigin_AWS_MANAGED       CertificateKeyPairOrigin = "AWS_MANAGED"
	CertificateKeyPairOrigin_CUSTOMER_PROVIDED CertificateKeyPairOrigin = "CUSTOMER_PROVIDED"
)

type CertificateManagedBy string

const (
	CertificateManagedBy_CLOUDFRONT CertificateManagedBy = "CLOUDFRONT"
)

type CertificateStatus_SDK string

const (
	CertificateStatus_SDK_EXPIRED              CertificateStatus_SDK = "EXPIRED"
	CertificateStatus_SDK_FAILED               CertificateStatus_SDK = "FAILED"
	CertificateStatus_SDK_INACTIVE             CertificateStatus_SDK = "INACTIVE"
	CertificateStatus_SDK_ISSUED               CertificateStatus_SDK = "ISSUED"
	CertificateStatus_SDK_PENDING_VALIDATION   CertificateStatus_SDK = "PENDING_VALIDATION"
	CertificateStatus_SDK_REVOKED              CertificateStatus_SDK = "REVOKED"
	CertificateStatus_SDK_VALIDATION_TIMED_OUT CertificateStatus_SDK = "VALIDATION_TIMED_OUT"
)

type CertificateTransparencyLoggingPreference string

const (
	CertificateTransparencyLoggingPreference_DISABLED CertificateTransparencyLoggingPreference = "DISABLED"
	CertificateTransparencyLoggingPreference_ENABLED  CertificateTransparencyLoggingPreference = "ENABLED"
)

type CertificateType string

const (
	CertificateType_AMAZON_ISSUED CertificateType = "AMAZON_ISSUED"
	CertificateType_IMPORTED      CertificateType = "IMPORTED"
	CertificateType_PRIVATE       CertificateType = "PRIVATE"
)

type ComparisonOperator string

const (
	ComparisonOperator_CONTAINS ComparisonOperator = "CONTAINS"
	ComparisonOperator_EQUALS   ComparisonOperator = "EQUALS"
)

type DomainScopeOption string

const (
	DomainScopeOption_DISABLED DomainScopeOption = "DISABLED"
	DomainScopeOption_ENABLED  DomainScopeOption = "ENABLED"
)

type DomainStatus string

const (
	DomainStatus_FAILED             DomainStatus = "FAILED"
	DomainStatus_PENDING_VALIDATION DomainStatus = "PENDING_VALIDATION"
	DomainStatus_SUCCESS            DomainStatus = "SUCCESS"
)

type ExtendedKeyUsageName string

const (
	ExtendedKeyUsageName_ANY                           ExtendedKeyUsageName = "ANY"
	ExtendedKeyUsageName_CODE_SIGNING                  ExtendedKeyUsageName = "CODE_SIGNING"
	ExtendedKeyUsageName_CUSTOM                        ExtendedKeyUsageName = "CUSTOM"
	ExtendedKeyUsageName_EMAIL_PROTECTION              ExtendedKeyUsageName = "EMAIL_PROTECTION"
	ExtendedKeyUsageName_IPSEC_END_SYSTEM              ExtendedKeyUsageName = "IPSEC_END_SYSTEM"
	ExtendedKeyUsageName_IPSEC_TUNNEL                  ExtendedKeyUsageName = "IPSEC_TUNNEL"
	ExtendedKeyUsageName_IPSEC_USER                    ExtendedKeyUsageName = "IPSEC_USER"
	ExtendedKeyUsageName_NONE                          ExtendedKeyUsageName = "NONE"
	ExtendedKeyUsageName_OCSP_SIGNING                  ExtendedKeyUsageName = "OCSP_SIGNING"
	ExtendedKeyUsageName_TIME_STAMPING                 ExtendedKeyUsageName = "TIME_STAMPING"
	ExtendedKeyUsageName_TLS_WEB_CLIENT_AUTHENTICATION ExtendedKeyUsageName = "TLS_WEB_CLIENT_AUTHENTICATION"
	ExtendedKeyUsageName_TLS_WEB_SERVER_AUTHENTICATION ExtendedKeyUsageName = "TLS_WEB_SERVER_AUTHENTICATION"
)

type FailureReason string

const (
	FailureReason_ADDITIONAL_VERIFICATION_REQUIRED FailureReason = "ADDITIONAL_VERIFICATION_REQUIRED"
	FailureReason_CAA_ERROR                        FailureReason = "CAA_ERROR"
	FailureReason_DOMAIN_NOT_ALLOWED               FailureReason = "DOMAIN_NOT_ALLOWED"
	FailureReason_DOMAIN_VALIDATION_DENIED         FailureReason = "DOMAIN_VALIDATION_DENIED"
	FailureReason_INVALID_PUBLIC_DOMAIN            FailureReason = "INVALID_PUBLIC_DOMAIN"
	FailureReason_NO_AVAILABLE_CONTACTS            FailureReason = "NO_AVAILABLE_CONTACTS"
	FailureReason_OTHER                            FailureReason = "OTHER"
	FailureReason_PCA_ACCESS_DENIED                FailureReason = "PCA_ACCESS_DENIED"
	FailureReason_PCA_INVALID_ARGS                 FailureReason = "PCA_INVALID_ARGS"
	FailureReason_PCA_INVALID_ARN                  FailureReason = "PCA_INVALID_ARN"
	FailureReason_PCA_INVALID_DURATION             FailureReason = "PCA_INVALID_DURATION"
	FailureReason_PCA_INVALID_STATE                FailureReason = "PCA_INVALID_STATE"
	FailureReason_PCA_LIMIT_EXCEEDED               FailureReason = "PCA_LIMIT_EXCEEDED"
	FailureReason_PCA_NAME_CONSTRAINTS_VALIDATION  FailureReason = "PCA_NAME_CONSTRAINTS_VALIDATION"
	FailureReason_PCA_REQUEST_FAILED               FailureReason = "PCA_REQUEST_FAILED"
	FailureReason_PCA_RESOURCE_NOT_FOUND           FailureReason = "PCA_RESOURCE_NOT_FOUND"
	FailureReason_SLR_NOT_FOUND                    FailureReason = "SLR_NOT_FOUND"
)

type KeyAlgorithm string

const (
	KeyAlgorithm_EC_prime256v1 KeyAlgorithm = "EC_prime256v1"
	KeyAlgorithm_EC_secp384r1  KeyAlgorithm = "EC_secp384r1"
	KeyAlgorithm_EC_secp521r1  KeyAlgorithm = "EC_secp521r1"
	KeyAlgorithm_RSA_1024      KeyAlgorithm = "RSA_1024"
	KeyAlgorithm_RSA_2048      KeyAlgorithm = "RSA_2048"
	KeyAlgorithm_RSA_3072      KeyAlgorithm = "RSA_3072"
	KeyAlgorithm_RSA_4096      KeyAlgorithm = "RSA_4096"
)

type KeyUsageName string

const (
	KeyUsageName_ANY                 KeyUsageName = "ANY"
	KeyUsageName_CERTIFICATE_SIGNING KeyUsageName = "CERTIFICATE_SIGNING"
	KeyUsageName_CRL_SIGNING         KeyUsageName = "CRL_SIGNING"
	KeyUsageName_CUSTOM              KeyUsageName = "CUSTOM"
	KeyUsageName_DATA_ENCIPHERMENT   KeyUsageName = "DATA_ENCIPHERMENT"
	KeyUsageName_DECIPHER_ONLY       KeyUsageName = "DECIPHER_ONLY"
	KeyUsageName_DIGITAL_SIGNATURE   KeyUsageName = "DIGITAL_SIGNATURE"
	KeyUsageName_ENCIPHER_ONLY       KeyUsageName = "ENCIPHER_ONLY"
	KeyUsageName_KEY_AGREEMENT       KeyUsageName = "KEY_AGREEMENT"
	KeyUsageName_KEY_ENCIPHERMENT    KeyUsageName = "KEY_ENCIPHERMENT"
	KeyUsageName_NON_REPUDIATION     KeyUsageName = "NON_REPUDIATION"
)

type PrevalidationType string

const (
	PrevalidationType_DNS_PREVALIDATION PrevalidationType = "DNS_PREVALIDATION"
)

type PublicKeyAlgorithm string

const (
	PublicKeyAlgorithm_EC_prime256v1 PublicKeyAlgorithm = "EC_prime256v1"
	PublicKeyAlgorithm_EC_secp384r1  PublicKeyAlgorithm = "EC_secp384r1"
	PublicKeyAlgorithm_RSA_2048      PublicKeyAlgorithm = "RSA_2048"
)

type RecordType string

const (
	RecordType_CNAME RecordType = "CNAME"
)

type RenewalEligibility string

const (
	RenewalEligibility_ELIGIBLE   RenewalEligibility = "ELIGIBLE"
	RenewalEligibility_INELIGIBLE RenewalEligibility = "INELIGIBLE"
)

type RenewalStatus string

const (
	RenewalStatus_FAILED               RenewalStatus = "FAILED"
	RenewalStatus_PENDING_AUTO_RENEWAL RenewalStatus = "PENDING_AUTO_RENEWAL"
	RenewalStatus_PENDING_VALIDATION   RenewalStatus = "PENDING_VALIDATION"
	RenewalStatus_SUCCESS              RenewalStatus = "SUCCESS"
)

type RevocationReason string

const (
	RevocationReason_AFFILIATION_CHANGED    RevocationReason = "AFFILIATION_CHANGED"
	RevocationReason_A_A_COMPROMISE         RevocationReason = "A_A_COMPROMISE"
	RevocationReason_CA_COMPROMISE          RevocationReason = "CA_COMPROMISE"
	RevocationReason_CERTIFICATE_HOLD       RevocationReason = "CERTIFICATE_HOLD"
	RevocationReason_CESSATION_OF_OPERATION RevocationReason = "CESSATION_OF_OPERATION"
	RevocationReason_KEY_COMPROMISE         RevocationReason = "KEY_COMPROMISE"
	RevocationReason_PRIVILEGE_WITHDRAWN    RevocationReason = "PRIVILEGE_WITHDRAWN"
	RevocationReason_REMOVE_FROM_CRL        RevocationReason = "REMOVE_FROM_CRL"
	RevocationReason_SUPERCEDED             RevocationReason = "SUPERCEDED"
	RevocationReason_SUPERSEDED             RevocationReason = "SUPERSEDED"
	RevocationReason_UNSPECIFIED            RevocationReason = "UNSPECIFIED"
)

type SearchCertificatesSortBy string

const (
	SearchCertificatesSortBy_ACME_ACCOUNT_ID             SearchCertificatesSortBy = "ACME_ACCOUNT_ID"
	SearchCertificatesSortBy_ACME_ENDPOINT_ARN           SearchCertificatesSortBy = "ACME_ENDPOINT_ARN"
	SearchCertificatesSortBy_CERTIFICATE_ARN             SearchCertificatesSortBy = "CERTIFICATE_ARN"
	SearchCertificatesSortBy_CERTIFICATE_KEY_PAIR_ORIGIN SearchCertificatesSortBy = "CERTIFICATE_KEY_PAIR_ORIGIN"
	SearchCertificatesSortBy_COMMON_NAME                 SearchCertificatesSortBy = "COMMON_NAME"
	SearchCertificatesSortBy_CREATED_AT                  SearchCertificatesSortBy = "CREATED_AT"
	SearchCertificatesSortBy_EXPORTED                    SearchCertificatesSortBy = "EXPORTED"
	SearchCertificatesSortBy_EXPORT_OPTION               SearchCertificatesSortBy = "EXPORT_OPTION"
	SearchCertificatesSortBy_IMPORTED_AT                 SearchCertificatesSortBy = "IMPORTED_AT"
	SearchCertificatesSortBy_IN_USE                      SearchCertificatesSortBy = "IN_USE"
	SearchCertificatesSortBy_ISSUED_AT                   SearchCertificatesSortBy = "ISSUED_AT"
	SearchCertificatesSortBy_KEY_ALGORITHM               SearchCertificatesSortBy = "KEY_ALGORITHM"
	SearchCertificatesSortBy_MANAGED_BY                  SearchCertificatesSortBy = "MANAGED_BY"
	SearchCertificatesSortBy_NOT_AFTER                   SearchCertificatesSortBy = "NOT_AFTER"
	SearchCertificatesSortBy_NOT_BEFORE                  SearchCertificatesSortBy = "NOT_BEFORE"
	SearchCertificatesSortBy_RENEWAL_ELIGIBILITY         SearchCertificatesSortBy = "RENEWAL_ELIGIBILITY"
	SearchCertificatesSortBy_RENEWAL_STATUS              SearchCertificatesSortBy = "RENEWAL_STATUS"
	SearchCertificatesSortBy_REVOKED_AT                  SearchCertificatesSortBy = "REVOKED_AT"
	SearchCertificatesSortBy_STATUS                      SearchCertificatesSortBy = "STATUS"
	SearchCertificatesSortBy_TYPE                        SearchCertificatesSortBy = "TYPE"
	SearchCertificatesSortBy_VALIDATION_METHOD           SearchCertificatesSortBy = "VALIDATION_METHOD"
)

type SearchCertificatesSortOrder string

const (
	SearchCertificatesSortOrder_ASCENDING  SearchCertificatesSortOrder = "ASCENDING"
	SearchCertificatesSortOrder_DESCENDING SearchCertificatesSortOrder = "DESCENDING"
)

type SortBy string

const (
	SortBy_CREATED_AT SortBy = "CREATED_AT"
)

type SortOrder string

const (
	SortOrder_ASCENDING  SortOrder = "ASCENDING"
	SortOrder_DESCENDING SortOrder = "DESCENDING"
)

type TimeType string

const (
	TimeType_DAYS    TimeType = "DAYS"
	TimeType_HOURS   TimeType = "HOURS"
	TimeType_MINUTES TimeType = "MINUTES"
)

type ValidationMethod string

const (
	ValidationMethod_DNS   ValidationMethod = "DNS"
	ValidationMethod_EMAIL ValidationMethod = "EMAIL"
	ValidationMethod_HTTP  ValidationMethod = "HTTP"
)
