// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	"github.com/aws/aws-sdk-go/aws"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = ackv1alpha1.AWSAccountID("")
)

// Contains ACM-specific metadata about a certificate.
type ACMCertificateMetadata struct {
	AcmeAccountID   *string `json:"acmeAccountID,omitempty"`
	AcmeEndpointARN *string `json:"acmeEndpointARN,omitempty"`
	// The origin of the certificate's key pair.
	CertificateKeyPairOrigin *string      `json:"certificateKeyPairOrigin,omitempty"`
	CreatedAt                *metav1.Time `json:"createdAt,omitempty"`
	ExportOption             *string      `json:"exportOption,omitempty"`
	Exported                 *bool        `json:"exported,omitempty"`
	ImportedAt               *metav1.Time `json:"importedAt,omitempty"`
	InUse                    *bool        `json:"inUse,omitempty"`
	IssuedAt                 *metav1.Time `json:"issuedAt,omitempty"`
	ManagedBy                *string      `json:"managedBy,omitempty"`
	RenewalEligibility       *string      `json:"renewalEligibility,omitempty"`
	RenewalStatus            *string      `json:"renewalStatus,omitempty"`
	RevokedAt                *metav1.Time `json:"revokedAt,omitempty"`
	Status                   *string      `json:"status,omitempty"`
	Type                     *string      `json:"type_,omitempty"`
	ValidationMethod         *string      `json:"validationMethod,omitempty"`
}

// Filters certificates by ACM metadata.
type ACMCertificateMetadataFilter struct {
	AcmeAccountID   *string `json:"acmeAccountID,omitempty"`
	AcmeEndpointARN *string `json:"acmeEndpointARN,omitempty"`
	// The origin of the certificate's key pair.
	CertificateKeyPairOrigin *string `json:"certificateKeyPairOrigin,omitempty"`
	ExportOption             *string `json:"exportOption,omitempty"`
	Exported                 *bool   `json:"exported,omitempty"`
	InUse                    *bool   `json:"inUse,omitempty"`
	ManagedBy                *string `json:"managedBy,omitempty"`
	RenewalStatus            *string `json:"renewalStatus,omitempty"`
	Status                   *string `json:"status,omitempty"`
	Type                     *string `json:"type_,omitempty"`
	ValidationMethod         *string `json:"validationMethod,omitempty"`
}

// Contains detailed information about an ACME account.
type AcmeAccount struct {
	AccountURL          *string      `json:"accountURL,omitempty"`
	CreatedAt           *metav1.Time `json:"createdAt,omitempty"`
	PublicKeyThumbprint *string      `json:"publicKeyThumbprint,omitempty"`
}

// Contains summary information about an ACME account.
type AcmeAccountSummary struct {
	AccountURL          *string      `json:"accountURL,omitempty"`
	CreatedAt           *metav1.Time `json:"createdAt,omitempty"`
	PublicKeyThumbprint *string      `json:"publicKeyThumbprint,omitempty"`
}

// Contains detailed information about an ACME domain validation.
type AcmeDomainValidation struct {
	AcmeEndpointARN *string      `json:"acmeEndpointARN,omitempty"`
	CreatedAt       *metav1.Time `json:"createdAt,omitempty"`
	UpdatedAt       *metav1.Time `json:"updatedAt,omitempty"`
}

// Contains summary information about an ACME domain validation.
type AcmeDomainValidationSummary struct {
	AcmeEndpointARN *string      `json:"acmeEndpointARN,omitempty"`
	CreatedAt       *metav1.Time `json:"createdAt,omitempty"`
	UpdatedAt       *metav1.Time `json:"updatedAt,omitempty"`
}

// Contains summary information about an ACME endpoint.
type AcmeEndpointSummary struct {
	AcmeEndpointARN       *string `json:"acmeEndpointARN,omitempty"`
	AuthorizationBehavior *string `json:"authorizationBehavior,omitempty"`
	// Defines the certificate authority to use for an ACME endpoint.
	CertificateAuthority *CertificateAuthority `json:"certificateAuthority,omitempty"`
	CertificateTags      []*Tag                `json:"certificateTags,omitempty"`
	Contact              *string               `json:"contact,omitempty"`
	CreatedAt            *metav1.Time          `json:"createdAt,omitempty"`
	EndpointURL          *string               `json:"endpointURL,omitempty"`
	FailureReason        *string               `json:"failureReason,omitempty"`
	Status               *string               `json:"status,omitempty"`
	UpdatedAt            *metav1.Time          `json:"updatedAt,omitempty"`
}

// Contains detailed information about an ACME endpoint.
type AcmeEndpoint_SDK struct {
	AcmeEndpointARN       *string `json:"acmeEndpointARN,omitempty"`
	AuthorizationBehavior *string `json:"authorizationBehavior,omitempty"`
	// Defines the certificate authority to use for an ACME endpoint.
	CertificateAuthority *CertificateAuthority `json:"certificateAuthority,omitempty"`
	CertificateTags      []*Tag                `json:"certificateTags,omitempty"`
	Contact              *string               `json:"contact,omitempty"`
	CreatedAt            *metav1.Time          `json:"createdAt,omitempty"`
	EndpointURL          *string               `json:"endpointURL,omitempty"`
	FailureReason        *string               `json:"failureReason,omitempty"`
	Status               *string               `json:"status,omitempty"`
	UpdatedAt            *metav1.Time          `json:"updatedAt,omitempty"`
}

// Contains detailed information about an ACME external account binding.
type AcmeExternalAccountBinding struct {
	AcmeEndpointARN *string      `json:"acmeEndpointARN,omitempty"`
	CreatedAt       *metav1.Time `json:"createdAt,omitempty"`
	ExpiresAt       *metav1.Time `json:"expiresAt,omitempty"`
	LastUsedAt      *metav1.Time `json:"lastUsedAt,omitempty"`
	RevokedAt       *metav1.Time `json:"revokedAt,omitempty"`
	UpdatedAt       *metav1.Time `json:"updatedAt,omitempty"`
}

// Contains summary information about an ACME external account binding.
type AcmeExternalAccountBindingSummary struct {
	AcmeEndpointARN *string      `json:"acmeEndpointARN,omitempty"`
	CreatedAt       *metav1.Time `json:"createdAt,omitempty"`
	ExpiresAt       *metav1.Time `json:"expiresAt,omitempty"`
	LastUsedAt      *metav1.Time `json:"lastUsedAt,omitempty"`
	RevokedAt       *metav1.Time `json:"revokedAt,omitempty"`
	UpdatedAt       *metav1.Time `json:"updatedAt,omitempty"`
}

// Defines the certificate authority to use for an ACME endpoint.
type CertificateAuthority struct {
	// Configuration for a public certificate authority.
	PublicCertificateAuthority *PublicCertificateAuthority `json:"publicCertificateAuthority,omitempty"`
}

// Contains metadata about an ACM certificate. This structure is returned in
// the response to a DescribeCertificate request.
type CertificateDetail struct {
	AcmeAccountID           *string `json:"acmeAccountID,omitempty"`
	AcmeEndpointARN         *string `json:"acmeEndpointARN,omitempty"`
	CertificateARN          *string `json:"certificateARN,omitempty"`
	CertificateAuthorityARN *string `json:"certificateAuthorityARN,omitempty"`
	// The origin of the certificate's key pair.
	CertificateKeyPairOrigin *string             `json:"certificateKeyPairOrigin,omitempty"`
	CreatedAt                *metav1.Time        `json:"createdAt,omitempty"`
	DomainName               *string             `json:"domainName,omitempty"`
	DomainValidationOptions  []*DomainValidation `json:"domainValidationOptions,omitempty"`
	ExtendedKeyUsages        []*ExtendedKeyUsage `json:"extendedKeyUsages,omitempty"`
	FailureReason            *string             `json:"failureReason,omitempty"`
	ImportedAt               *metav1.Time        `json:"importedAt,omitempty"`
	InUseBy                  []*string           `json:"inUseBy,omitempty"`
	IssuedAt                 *metav1.Time        `json:"issuedAt,omitempty"`
	Issuer                   *string             `json:"issuer,omitempty"`
	KeyAlgorithm             *string             `json:"keyAlgorithm,omitempty"`
	KeyUsages                []*KeyUsage         `json:"keyUsages,omitempty"`
	ManagedBy                *string             `json:"managedBy,omitempty"`
	NotAfter                 *metav1.Time        `json:"notAfter,omitempty"`
	NotBefore                *metav1.Time        `json:"notBefore,omitempty"`
	// Structure that contains options for your certificate. You can use this structure
	// to specify whether to export your certificate.
	//
	// Certificate transparency logging opt-out is no longer available. All public
	// certificates are recorded in a certificate transparency log. For general
	// information, see Certificate Transparency Logging (https://docs.aws.amazon.com/acm/latest/userguide/acm-concepts.html#concept-transparency).
	//
	// You can export public ACM certificates to use with Amazon Web Services services
	// as well as outside Amazon Web Services Cloud. For more information, see Certificate
	// Manager exportable public certificate (https://docs.aws.amazon.com/acm/latest/userguide/acm-exportable-certificates.html).
	Options            *CertificateOptions `json:"options,omitempty"`
	RenewalEligibility *string             `json:"renewalEligibility,omitempty"`
	// Contains information about the status of ACM's managed renewal (https://docs.aws.amazon.com/acm/latest/userguide/acm-renewal.html)
	// for the certificate. This structure exists only when the certificate type
	// is AMAZON_ISSUED.
	RenewalSummary          *RenewalSummary `json:"renewalSummary,omitempty"`
	RevocationReason        *string         `json:"revocationReason,omitempty"`
	RevokedAt               *metav1.Time    `json:"revokedAt,omitempty"`
	Serial                  *string         `json:"serial,omitempty"`
	SignatureAlgorithm      *string         `json:"signatureAlgorithm,omitempty"`
	Status                  *string         `json:"status,omitempty"`
	Subject                 *string         `json:"subject,omitempty"`
	SubjectAlternativeNames []*string       `json:"subjectAlternativeNames,omitempty"`
	Type                    *string         `json:"type_,omitempty"`
}

// Defines a filter for searching certificates by ARN, X.509 attributes, or
// ACM metadata.
type CertificateFilter struct {
	CertificateARN *string `json:"certificateARN,omitempty"`
}

// Structure that contains options for your certificate. You can use this structure
// to specify whether to export your certificate.
//
// Certificate transparency logging opt-out is no longer available. All public
// certificates are recorded in a certificate transparency log. For general
// information, see Certificate Transparency Logging (https://docs.aws.amazon.com/acm/latest/userguide/acm-concepts.html#concept-transparency).
//
// You can export public ACM certificates to use with Amazon Web Services services
// as well as outside Amazon Web Services Cloud. For more information, see Certificate
// Manager exportable public certificate (https://docs.aws.amazon.com/acm/latest/userguide/acm-exportable-certificates.html).
type CertificateOptions struct {
	CertificateTransparencyLoggingPreference *string `json:"certificateTransparencyLoggingPreference,omitempty"`
	Export                                   *string `json:"export,omitempty"`
}

// Contains information about a certificate returned by the SearchCertificates
// action. This structure includes the certificate ARN, X.509 attributes, and
// ACM metadata.
type CertificateSearchResult struct {
	CertificateARN *string `json:"certificateARN,omitempty"`
}

// This structure is returned in the response object of ListCertificates action.
type CertificateSummary struct {
	CertificateARN *string `json:"certificateARN,omitempty"`
	// The origin of the certificate's key pair.
	CertificateKeyPairOrigin             *string      `json:"certificateKeyPairOrigin,omitempty"`
	CreatedAt                            *metav1.Time `json:"createdAt,omitempty"`
	DomainName                           *string      `json:"domainName,omitempty"`
	ExportOption                         *string      `json:"exportOption,omitempty"`
	Exported                             *bool        `json:"exported,omitempty"`
	ExtendedKeyUsages                    []*string    `json:"extendedKeyUsages,omitempty"`
	HasAdditionalSubjectAlternativeNames *bool        `json:"hasAdditionalSubjectAlternativeNames,omitempty"`
	ImportedAt                           *metav1.Time `json:"importedAt,omitempty"`
	InUse                                *bool        `json:"inUse,omitempty"`
	IssuedAt                             *metav1.Time `json:"issuedAt,omitempty"`
	KeyAlgorithm                         *string      `json:"keyAlgorithm,omitempty"`
	KeyUsages                            []*string    `json:"keyUsages,omitempty"`
	ManagedBy                            *string      `json:"managedBy,omitempty"`
	NotAfter                             *metav1.Time `json:"notAfter,omitempty"`
	NotBefore                            *metav1.Time `json:"notBefore,omitempty"`
	RenewalEligibility                   *string      `json:"renewalEligibility,omitempty"`
	RevokedAt                            *metav1.Time `json:"revokedAt,omitempty"`
	Status                               *string      `json:"status,omitempty"`
	SubjectAlternativeNameSummaries      []*string    `json:"subjectAlternativeNameSummaries,omitempty"`
	Type                                 *string      `json:"type_,omitempty"`
}

// Defines the X.500 relative distinguished name (RDN).
type CustomAttribute struct {
	ObjectIdentifier *string `json:"objectIdentifier,omitempty"`
	Value            *string `json:"value,omitempty"`
}

// DNS prevalidation details including the resource record for validation.
type DNSPrevalidationDetails struct {
	// Contains a DNS record value that you can use to validate ownership or control
	// of a domain. This is used by the DescribeCertificate action.
	ResourceRecord *ResourceRecord `json:"resourceRecord,omitempty"`
}

// Contains X.500 distinguished name information.
type DistinguishedName struct {
	CommonName                 *string `json:"commonName,omitempty"`
	Country                    *string `json:"country,omitempty"`
	DistinguishedNameQualifier *string `json:"distinguishedNameQualifier,omitempty"`
	GenerationQualifier        *string `json:"generationQualifier,omitempty"`
	GivenName                  *string `json:"givenName,omitempty"`
	Initials                   *string `json:"initials,omitempty"`
	Locality                   *string `json:"locality,omitempty"`
	Organization               *string `json:"organization,omitempty"`
	OrganizationalUnit         *string `json:"organizationalUnit,omitempty"`
	Pseudonym                  *string `json:"pseudonym,omitempty"`
	SerialNumber               *string `json:"serialNumber,omitempty"`
	State                      *string `json:"state,omitempty"`
	Surname                    *string `json:"surname,omitempty"`
	Title                      *string `json:"title,omitempty"`
}

// Contains information about the validation of each domain name in the certificate.
type DomainValidation struct {
	DomainName *string `json:"domainName,omitempty"`
	// Contains information for HTTP-based domain validation of certificates requested
	// through Amazon CloudFront and issued by ACM. This field exists only when
	// the certificate type is AMAZON_ISSUED and the validation method is HTTP.
	HTTPRedirect *HTTPRedirect `json:"httpRedirect,omitempty"`
	// Contains a DNS record value that you can use to validate ownership or control
	// of a domain. This is used by the DescribeCertificate action.
	ResourceRecord   *ResourceRecord `json:"resourceRecord,omitempty"`
	ValidationDomain *string         `json:"validationDomain,omitempty"`
	ValidationEmails []*string       `json:"validationEmails,omitempty"`
	ValidationMethod *string         `json:"validationMethod,omitempty"`
	ValidationStatus *string         `json:"validationStatus,omitempty"`
}

// Contains information about the domain names that you want ACM to use to send
// you emails that enable you to validate domain ownership.
type DomainValidationOption struct {
	DomainName       *string `json:"domainName,omitempty"`
	ValidationDomain *string `json:"validationDomain,omitempty"`
}

// The Extended Key Usage X.509 v3 extension defines one or more purposes for
// which the public key can be used. This is in addition to or in place of the
// basic purposes specified by the Key Usage extension.
type ExtendedKeyUsage struct {
	Name *string `json:"name,omitempty"`
	OID  *string `json:"oid,omitempty"`
}

// Contains details about a failure.
type FailureDetails struct {
	Message *string `json:"message,omitempty"`
}

// This structure can be used in the ListCertificates action to filter the output
// of the certificate list.
type Filters struct {
	ExportOption     *string   `json:"exportOption,omitempty"`
	ExtendedKeyUsage []*string `json:"extendedKeyUsage,omitempty"`
	KeyTypes         []*string `json:"keyTypes,omitempty"`
	KeyUsage         []*string `json:"keyUsage,omitempty"`
	ManagedBy        *string   `json:"managedBy,omitempty"`
}

// Describes an ASN.1 X.400 GeneralName as defined in RFC 5280 (https://datatracker.ietf.org/doc/html/rfc5280).
// Only one of the following naming options should be provided.
type GeneralName struct {
	DNSName                   *string `json:"dnsName,omitempty"`
	IPAddress                 *string `json:"ipAddress,omitempty"`
	RegisteredID              *string `json:"registeredID,omitempty"`
	RFC822Name                *string `json:"rfc822Name,omitempty"`
	UniformResourceIdentifier *string `json:"uniformResourceIdentifier,omitempty"`
}

// Contains information for HTTP-based domain validation of certificates requested
// through Amazon CloudFront and issued by ACM. This field exists only when
// the certificate type is AMAZON_ISSUED and the validation method is HTTP.
type HTTPRedirect struct {
	RedirectFrom *string `json:"redirectFrom,omitempty"`
	RedirectTo   *string `json:"redirectTo,omitempty"`
}

// The Key Usage X.509 v3 extension defines the purpose of the public key contained
// in the certificate.
type KeyUsage struct {
	Name *string `json:"name,omitempty"`
}

// Defines a custom ASN.1 X.400 GeneralName using an object identifier (OID)
// and value. For more information, see NIST's definition of Object Identifier
// (OID) (https://csrc.nist.gov/glossary/term/Object_Identifier).
type OtherName struct {
	ObjectIdentifier *string `json:"objectIdentifier,omitempty"`
	Value            *string `json:"value,omitempty"`
}

// Configuration for a public certificate authority.
type PublicCertificateAuthority struct {
	AllowedKeyAlgorithms []*string `json:"allowedKeyAlgorithms,omitempty"`
}

// Contains information about the status of ACM's managed renewal (https://docs.aws.amazon.com/acm/latest/userguide/acm-renewal.html)
// for the certificate. This structure exists only when the certificate type
// is AMAZON_ISSUED.
type RenewalSummary struct {
	DomainValidationOptions []*DomainValidation `json:"domainValidationOptions,omitempty"`
	RenewalStatus           *string             `json:"renewalStatus,omitempty"`
	RenewalStatusReason     *string             `json:"renewalStatusReason,omitempty"`
	UpdatedAt               *metav1.Time        `json:"updatedAt,omitempty"`
}

// Contains a DNS record value that you can use to validate ownership or control
// of a domain. This is used by the DescribeCertificate action.
type ResourceRecord struct {
	Name  *string `json:"name,omitempty"`
	Type  *string `json:"type_,omitempty"`
	Value *string `json:"value,omitempty"`
}

// A key-value pair that identifies or specifies metadata about an ACM resource.
type Tag struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// Specifies a time range for filtering certificates.
type TimestampRange struct {
	End   *metav1.Time `json:"end,omitempty"`
	Start *metav1.Time `json:"start,omitempty"`
}

// Filters certificates by X.509 attributes.
type X509AttributeFilter struct {
	ExtendedKeyUsage *string `json:"extendedKeyUsage,omitempty"`
	KeyAlgorithm     *string `json:"keyAlgorithm,omitempty"`
	KeyUsage         *string `json:"keyUsage,omitempty"`
}

// Contains X.509 certificate attributes extracted from the certificate.
type X509Attributes struct {
	ExtendedKeyUsages []*string    `json:"extendedKeyUsages,omitempty"`
	KeyAlgorithm      *string      `json:"keyAlgorithm,omitempty"`
	KeyUsages         []*string    `json:"keyUsages,omitempty"`
	NotAfter          *metav1.Time `json:"notAfter,omitempty"`
	NotBefore         *metav1.Time `json:"notBefore,omitempty"`
}
